### ISSUE TITLE
Missing Broodwar.dll.config

### ISSUE THREAD

**Issue by MarcoMeter** [Lamarth/BWAPI-CLI#1]
"Edit .config file. Assembly key must point to your AI assembly (with extension), and Module key must point to class, which implements AiBase."

I build all of the projects, but none of them created that mentioned config file. Where is the Broodwar.dll.config coming from?

**Comment by Lamarth** [comment]
I don't have a Broodwar.dll.config, but I do have a BroodwarLoader.dll.config that is pointing as instructed.

**Comment by MarcoMeter** [comment]
Your readme.md confused me pretty well about that. It'd be nice if you could update the instructions that it is all about the BroodwarLoader and not Broodwar.

![path](https://cloud.githubusercontent.com/assets/6996955/14487790/ec0f8e50-0164-11e6-879e-fdc977f33279.png)
