### ISSUE TITLE
Position somewhat represents only (0,0) used in PingMiniMap, Attack, Move, Rightclick

### ISSUE THREAD

**Issue by MarcoMeter** [Lamarth/BWAPI-CLI#2]
While implementing some simple logic to let units attack some point, all the units (where I triggered Attack, Move or Rightclick) kept moving to (0,0).

This behavior applies to the function Game.PingMiniMap as well. So calling this line
`Game.PingMinimap(new Position(120, 80));`
inside the ExampleAiModule executes a ping on the mini map at (0,0).

This is the code snippet should combat units attack the opposing start location
`public void ForceAttack(TilePosition targetPosition)
        {
            foreach(AiCombatUnitBehavior unit in combatUnits)
            {
                Position pos = new Position(targetPosition.X, targetPosition.Y);
                unit.GetUnit().Move(pos, false);
            }
        }`

So I guess there is something going wrong with the Position object. Printing the coordinates works as suspected. But executing any function which receives a position parameter doesn't seem to get the right coordinates.

**Comment by Lamarth** [comment]
TilePosition and Position are very different. You need to convert between them by multiplying by 32. There should be a convenient constant lying around, and maybe some conversion functions.
